### ISSUE TITLE
chm_lib.h not included in chm/ directory

### ISSUE THREAD

**Issue by MayerDaniel** [dottedmag/pychm#17]
When attempting to build on my machine, GCC errors out. `chmlib_search.h` contains the following `include`:

```
#include <chm_lib.h>
```

This header file is not included in the repo. Would you kindly commit this file? Thank you!

**Comment by dottedmag** [comment]
https://github.com/dottedmag/pychm/blob/master/INSTALL#L8

**Comment by MayerDaniel** [comment]
Ah so pip installing this package is not supported? Thank you for the quick response

**Comment by dottedmag** [comment]
It is, but pip can't pull C libraries — you have to have them installed on your system already.
