### ISSUE TITLE
Cannot retrieve topics tree for some MSDN 1999 CHM archives

### ISSUE THREAD

**Issue by huntertur** [dottedmag/pychm#25]
Hello :) Thank you for the great feature-rich wrapper over chmlib that you provide. I have been working on a project to catalog many of the old Microsoft KB articles that are no longer available on its website, and as part of this, I've been using pychm to process the CHM files on Microsoft development tool CDs since those discs tend to contain copies of tens of thousands of the old articles each. During this work, I've encountered issues loading the topics tree on 2 of the 25 CHM files that make up the KB articles on the MSDN Library 1999 disc.

# Reproduction steps

1. Obtain the MSDN Library 1999 disc through your preferred method. It may be labeled October 1999. (Disc image size 2,159,572,992 bytes; sha256sum hash `830d37b7e46c903a634c377274cb01cf18273e431e5492127a47fcfbe4e19f1a`)
2. Copy either `/MSDN/kbfortrn.chm` or `/MSDN/kbintdev.chm` to the working directory.
3. Run the following script with the path to the copied CHM file as the sole argument:

```python
#!/usr/bin/env python3

import sys

from chm.chm import CHMFile

if len(sys.argv) < 2:
    print(f'usage: {sys.argv[0]} filename', file=sys.stderr)
    sys.exit(1)

filename = sys.argv[1]
file = CHMFile()

if not file.LoadCHM(filename):
    print('LoadCHM returned 0', file=sys.stderr)
    sys.exit(1)

print(f'{file.GetTopicsTree()}')
```

# Expected output

The topics tree is printed. Use any of the 23 other `kb`-prefixed files on the disc, such as `kbasm.chm`, to verify this behavior.

# Actual output

`None` is printed.

# Notes from investigating

It seems like pychm makes an assumption[[1]] that the basename of the topics file is always identical to the value of Compiled File in `/#SYSTEM`. This is usually true, but for these two files, it is not; the topics tree for `kbfortrn.chm` is at `/kbfortn.hhc`, and for `kbintdev.chm` at `/kbinterdev.hhc`. Looking at the spec[[2]], it seems like the Binary Index field (11) for `/#SYSTEM` might be the key, but unfortunately, the table that it points to is only present in the companion `.chi` files that are next to the `.chm` files. As a test, I pulled out a Windows 98 Second Edition computer and attempted opening the affected `.chm` files with and without their companion files present. When they are present, the topics tree is present; when they aren't, it isn't. So, unfortunately, the `.chi` files are crucial here.

[1]: https://github.com/dottedmag/pychm/blob/85debe1b6b620c0d3ff5027594855334996b925f/chm/chm.py#L289
[2]: https://www.nongnu.org/chmspec/latest/Internal.html#SYSTEM

# Potential paths to fixing

It looks like the `.chi` files are in the same format as the `.chm` files, which is good. When I call `LoadCHM()` on one of the affected `.chm` files, `.topics` is unset, but with the `.chi`, `.topics` is set to the correct path for the `.chm`. And, if I set the `.topics` for the `.chm`-loaded `CHMFile` to the value of `.topics` for the `.chi`-loaded `CHMFile` and then call `GetTopicsTree()` on the `.chm`-loaded `CHMFile`, I am able to get the topics tree as expected.

I understand pychm needs a new maintainer (#20). I would be willing to look into implementing the needed functionality to handle companion files, at least in the topics tree case. However, before I do start working on a patch, what is the preferred API design for something like this?

- don't implement anything, and instead mention what the client code needs to do in the documentation
- add a blank-default `companionName` parameter to `LoadCHM`, and double `CHMFile`'s amount of state it keeps track of
- add a new wrapper `CHMCollection` class that would "merge" the components of all of the loaded files together (the same spec suggests a given `.chm` could have several companion files[[3]]), which would leave `CHMFile` alone but result in its interface being duplicated by a new class

[3]: https://www.nongnu.org/chmspec/latest/Content.html

Again, thank you for your work on the library!

**Comment by dottedmag** [comment]
Hello Hunter. `CHMCollection` looks like a right way to go.
