### ISSUE TITLE
MacOS install pychm error!

### ISSUE THREAD

**Issue by hkcyl123** [dottedmag/pychm#27]
Terminal run pip install pychm after:

Collecting pychm
  Using cached pychm-0.8.6.tar.gz (19 kB)
Building wheels for collected packages: pychm
  Building wheel for pychm (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/xx/opt/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/qj/qq5nj5xn30b1g7lylty9wjfc0000gn/T/pip-install-p3fbn5fw/pychm_09e72dff3b0943b79c8686cc0f2e3858/setup.py'"'"'; __file__='"'"'/private/var/folders/qj/qq5nj5xn30b1g7lylty9wjfc0000gn/T/pip-install-p3fbn5fw/pychm_09e72dff3b0943b79c8686cc0f2e3858/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/qj/qq5nj5xn30b1g7lylty9wjfc0000gn/T/pip-wheel-f13g_5sf
       cwd: /private/var/folders/qj/qq5nj5xn30b1g7lylty9wjfc0000gn/T/pip-install-p3fbn5fw/pychm_09e72dff3b0943b79c8686cc0f2e3858/
  Complete output (21 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.9
  creating build/lib.macosx-10.9-x86_64-3.9/chm
  copying chm/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/chm
  copying chm/chm.py -> build/lib.macosx-10.9-x86_64-3.9/chm
  copying chm/chmlib.py -> build/lib.macosx-10.9-x86_64-3.9/chm
  copying chm/extra.py -> build/lib.macosx-10.9-x86_64-3.9/chm
  running build_ext
  building 'chm._chmlib' extension
  creating build/temp.macosx-10.9-x86_64-3.9
  creating build/temp.macosx-10.9-x86_64-3.9/chm
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/xx/opt/anaconda3/include -arch x86_64 -I/Users/xx/opt/anaconda3/include -fPIC -O2 -isystem /Users/xx/opt/anaconda3/include -arch x86_64 -I/Users/xx/opt/anaconda3/include/python3.9 -c chm/_chmlib.c -o build/temp.macosx-10.9-x86_64-3.9/chm/_chmlib.o
  In file included from chm/_chmlib.c:4:
  chm/chmlib_search.h:4:10: fatal error: 'chm_lib.h' file not found
  #include <chm_lib.h>
           ^~~~~~~~~~~
  1 error generated.
  error: command '/usr/bin/clang' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for pychm
  Running setup.py clean for pychm
Failed to build pychm
Installing collected packages: pychm
    Running setup.py install for pychm ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/xx/opt/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/qj/qq5nj5xn30b1g7lylty9wjfc0000gn/T/pip-install-p3fbn5fw/pychm_09e72dff3b0943b79c8686cc0f2e3858/setup.py'"'"'; __file__='"'"'/private/var/folders/qj/qq5nj5xn30b1g7lylty9wjfc0000gn/T/pip-install-p3fbn5fw/pychm_09e72dff3b0943b79c8686cc0f2e3858/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/qj/qq5nj5xn30b1g7lylty9wjfc0000gn/T/pip-record-heunnlv6/install-record.txt --single-version-externally-managed --compile --install-headers /Users/xx/opt/anaconda3/include/python3.9/pychm
         cwd: /private/var/folders/qj/qq5nj5xn30b1g7lylty9wjfc0000gn/T/pip-install-p3fbn5fw/pychm_09e72dff3b0943b79c8686cc0f2e3858/
    Complete output (21 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.9
    creating build/lib.macosx-10.9-x86_64-3.9/chm
    copying chm/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/chm
    copying chm/chm.py -> build/lib.macosx-10.9-x86_64-3.9/chm
    copying chm/chmlib.py -> build/lib.macosx-10.9-x86_64-3.9/chm
    copying chm/extra.py -> build/lib.macosx-10.9-x86_64-3.9/chm
    running build_ext
    building 'chm._chmlib' extension
    creating build/temp.macosx-10.9-x86_64-3.9
    creating build/temp.macosx-10.9-x86_64-3.9/chm
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/xx/opt/anaconda3/include -arch x86_64 -I/Users/xx/opt/anaconda3/include -fPIC -O2 -isystem /Users/xx/opt/anaconda3/include -arch x86_64 -I/Users/xx/opt/anaconda3/include/python3.9 -c chm/_chmlib.c -o build/temp.macosx-10.9-x86_64-3.9/chm/_chmlib.o
    In file included from chm/_chmlib.c:4:
    chm/chmlib_search.h:4:10: fatal error: 'chm_lib.h' file not found
    #include <chm_lib.h>
             ^~~~~~~~~~~
    1 error generated.
    error: command '/usr/bin/clang' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/xx/opt/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/qj/qq5nj5xn30b1g7lylty9wjfc0000gn/T/pip-install-p3fbn5fw/pychm_09e72dff3b0943b79c8686cc0f2e3858/setup.py'"'"'; __file__='"'"'/private/var/folders/qj/qq5nj5xn30b1g7lylty9wjfc0000gn/T/pip-install-p3fbn5fw/pychm_09e72dff3b0943b79c8686cc0f2e3858/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/qj/qq5nj5xn30b1g7lylty9wjfc0000gn/T/pip-record-heunnlv6/install-record.txt --single-version-externally-managed --compile --install-headers /Users/xx/opt/anaconda3/include/python3.9/pychm Check the logs for full command output.

**Comment by dottedmag** [comment]
Please read the project's README.
